---
title: "First Knit"
author: "Matias Lucha"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I went to The Palmdale Aerospace Academy, graduated in 2023. Math was definitely easier and more black and white in its concepts. English varied on the teacher and the rules constantly changed. I did best in science and health classes. I was attracted to the sciences and anatomy. 
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   
I have an HP with Windows. I am about a 6 with computer knowledge. I know basic things but also can figure and finess my way around a problem. I have a good wifi connection with hardly any lack of wifi.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   
 I usually go by my last name: Lucha (lew-cha). It is easier to pronounce. 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
 I plan to become a firefighter with the ultimate goal of becoming a Paramedic or a Captain for a squad. I am interested in the college class of AVC Fire Academy, in order to get my Firefighter 1 certification.




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  Yes I have been all across Europe, I have visited Canada and Mexico. I have never been in the military. But if I were to join a branch of the military I would join choose Marines because they are the closest to a firefighter in body maintenance and difficulty in training.  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I am in Math 115 because it is a requirement for my general education. I do not plan on transfering for my degree. I plan on getting any possible passing grade for this class, turning in the work properly and on time and doing what needs to be done. 
 






  




